# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec9d4fea5e291bb972df247240f06c26b87f00ecec095fd181287b0cc0e71fe3dee2ad8edcccfe580aa4eb7796f7cf39751824b53c5a05fafcd5af8e668fccb

test:
  secret_key_base: 193698a0f8c2f622afdfdb413517a40ea2440214e0ddfcb3a67039d3d78eea1803a04be2fec1f60d14fbfee611c4f5d9c83dc563b1d88717ea698bbc1cf60ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
